services:
    knp_rad_view_renderer.event_listener.view_listener:
        class: Knp\Rad\ViewRenderer\EventListener\ViewListener
        arguments:
            - []
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onView }

    knp_rad_view_renderer.renderer.controller_renderer:
        class: Knp\Rad\ViewRenderer\Renderer\ControllerRenderer
        arguments:
            - @request_stack
            - @knp_rad_view_renderer.renderer.twig_renderer
            - @knp_rad_view_renderer.controller.guesser
        tags:
            - { name: knp_rad_view_renderer.renderer }

    knp_rad_view_renderer.renderer.rest_renderer:
        class: Knp\Rad\ViewRenderer\Renderer\RestRenderer
        arguments:
            - @request_stack
        tags:
            - { name: knp_rad_view_renderer.renderer }

    knp_rad_view_renderer.renderer.twig_renderer:
        class: Knp\Rad\ViewRenderer\Renderer\TwigRenderer
        arguments:
            - @templating
        tags:
            - { name: knp_rad_view_renderer.renderer }

    knp_rad_view_renderer.controller.guesser:
        class: Knp\Rad\ViewRenderer\Controller\Guesser
        arguments:
          - @service_container
          - @controller_name_converter
